language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

before_install:

install:
  - npm install

before_script:

script:
  - npm run lint
  # - npm test -- --watchAll=false
  - bash ./travis/deploy.sh

after_success:

before_deploy:

deploy:

after_deploy:

after_script:
